refactor: improve global architecture
fastify/demo pull request #54
Opened 2024-11-08 15:03 UTC by Turn0xx

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)
#52

2024-11-08 15:21 UTC, Turn0xx commented
This PR introduces a modular architecture, organized by functional domains. 
Each modules encapsulate its own declarations / definitions.


This is the actual structure that i'm going to follow: 

```
modules
├── accounts
│   ├── index.route.ts
├── auth
│   ├── auth.service.ts
│   ├── controllers
│   │   ├── index.ts
│   │   └── login.controller.ts
│   ├── index.route.ts
└── tasks
       ├── index.route.ts
```

Each `module` is going to have 
 - A bunch of controllers (generally one controller per route), who consumes services through the fastify instance.
 - One or more services, implemented as plugins.
 - Route file that serve as the api entry points
 
 Wdyt on this approach ?

2024-11-08 17:52 UTC, Turn0xx commented
@jean-michelet You mean to much for the auth module or for all modules ? yeah for auth module just an index file would do the work. However i think for other modules like tasks, we can create multiple controller files per action area.

2024-11-08 17:55 UTC, jean-michelet commented
Are you sure it will not break ts inference? One file by controller function is too much I think.

2024-11-08 18:21 UTC, Turn0xx commented
> Are you sure it will not break ts inference? 
What do you mean by ts inference ?

> One file by controller function is too much I think.
It's not really one file by controller function but one file by action area.
But for this demo you are right there is not really a lot of actions area per module so i'm going to make just 1 file.

And the same thing for services i think.

2025-01-12 12:49 UTC, mcollina requested changes

2025-01-12 12:49 UTC, mcollina commented on src/modules/auth/index.route.ts
> +  fastify.post('', {}, authController.login)
This is an antipattern. You are splitting the route code from its definitions, and you shouldn't really do that at all, as they are tightly coupled together.

2025-03-15 10:21 UTC, jean-michelet commented
I think it would be better to create a new repository using an IoC container to provide examples of how to implement a hexagonal architecture with Fastify. Something using the [awilix](https://github.com/fastify/fastify-awilix) plugin. I could even create a boilerplate that simplifies container construction and allows overriding services for testing purposes.  

This demo is intended for a broad audience that doesn’t necessarily master or have an interest in these practices.

2025-04-14 19:56 UTC, closed without merging

2025-04-14 19:56 UTC, jean-michelet commented
Close due to inactivity.